version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_API_SERVICE_URL: "http://18.208.196.7:30001"

phases:
  install:
    runtime-versions:
      python: 3.9

    commands:
      - echo "Installing Docker 18..."
      - curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-18.09.9.tgz -o docker.tgz
      - tar xzvf docker.tgz
      - mv docker/* /usr/bin/
      - dockerd &
      - while(! docker stats --no-stream ); do echo "Waiting for Docker to start..."; sleep 1; done
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building prod images..."
      - docker-compose up -d --build
      - >
        docker build \
          -f be/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:prod \
          ./be
      - >
        docker build \
          -f fe/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./fe

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:prod
