version: '3.1'

services:
  redis:
    image: public.ecr.aws/docker/library/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - backend

  fe:
    stdin_open: true
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - REACT_APP_BE_NETWORK=backend
      - REACT_APP_BE_PORT=5000
      - REACT_APP_API_SERVICE_URL=http://be:5000
    depends_on:
      - be
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
