FROM nginx
COPY build /usr/share/nginx/html
#ENV REACT_APP_BE_NETWORK http://192.168.99.105
#ENV REACT_APP_BE_PORT 5004


FROM nginx
COPY build /usr/share/nginx/html
ENV BE_NETWORK http://localhost
ENV BE_PORT 5004