apiVersion: v1
kind: Service
metadata:
  name: twtr-be-service
spec:
  type: LoadBalancer
  selector:
    app: twtr-be
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP



# apiVersion: v1
# kind: Service
# metadata:
#   name: twtr-be-service
# spec:
#   type: LoadBalancer  # Change to LoadBalancer
#   selector:
#     app: twtr-be
#   ports:
#     - port: 5000
#       targetPort: 5000
#       protocol: TCP
