apiVersion: v1
kind: Service
metadata:
  name: twtr-fe-service
spec:
  type: LoadBalancer
  selector:
    app: twtr-fe
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP



# apiVersion: v1
# kind: Service
# metadata:
#   name: twtr-fe-service
# spec:
#   type: LoadBalancer  # Change to LoadBalancer
#   selector:
#     app: twtr-fe
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
